catalog/urls.py
#coding=utf-8

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.product_list,name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$',views.category,name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$',views.product,name='product'),

]

checkout/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$',views.create_cartitem,name='create_cartitem')
]

djangoecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^contato/$',views.contact,name='contact'),
    url(r'^produto/$',views.product,name='product'),
    url(r'^entrar/$',login,{'template_name':'login.html'},name='login'),
    url(r'^sair/$',logout,{'next_page':'index'},name='logout'),
    url(r'^produtos/',include('catalog.urls',namespace='catalog')),
    url(r'^conta/',include('accounts.urls',namespace='accounts')),
    url(r'^compras/',include('checkout.urls',namespace='checkout')),
        url(r'^admin/', admin.site.urls),
]

catalog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField('Nome',max_length=100)
    slug = models.SlugField('Identificador',max_length=100)

    created = models.DateTimeField('Criado em',auto_now_add=True)
    modified = models.DateTimeField('Modificado em',auto_now=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']

    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('catalog:category',kwargs={'slug':self.slug})

class Product(models.Model):
    name = models.CharField('Nome',max_length=100)
    slug = models.SlugField('Identificador',max_length=100)
    category = models.ForeignKey('catalog.Category',verbose_name='Categoria')
    description = models.TextField('Descrição',blank=True)
    price = models.DecimalField('Preço',decimal_places=2,max_digits=8)

    created = models.DateTimeField('Criado em',auto_now_add=True)
    modified = models.DateTimeField('Modificado em',auto_now=True)

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product',kwargs={'slug':self.slug})

catalog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from .models import Product, Category
from django.views import generic

# Create your views here.

class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    paginate_by = 3

product_list = ProductListView.as_view()

class CategoryListView(generic.ListView):
    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        category = get_object_or_404(Category,slug=self.kwargs['slug'])
        return Product.objects.filter(category=category)

    def get_context_data(self, **kwargs):
        context = super(CategoryListView,self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(Category,slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()

def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product
    }
    return render(request,'catalog/product.html',context)

catalog/templates/catalog/_product.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <a href="{{product.get_absolute_url}}">
        <img src="http://placehold.it/350x250" alt="" />
      </a>
      <div class="caption">
        <h3>{{ product.name }}</h3>
        <p>{{product.description|linebreaks}}</p>
        <p><a href="{{product.get_absolute_url}}" class="btn btn-success" role="button">Comprar</a> <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default" role="button">Adicionar ao Carrinho</a></p>
      </div>
    </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}
{% load pagination %}
{% block titulo %}
  {{current_category}} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{current_category}}</h1>
</div>
<div class="row">
  {% for product in product_list  %}
  {% include "catalog/_product.html" %}
  {% endfor %}
</div>
    {% pagination request paginator page_obj %}
{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}

{% block titulo %}
  {{ product }} | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>{{product}}</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <a href="#" class="thumbnail">
      <img src="http://placehold.it/350x250" alt="" />
    </a>
  </div>
  <div class="col-sm-8">
      <p class="text-right">
          <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-success">Adicionar ao Carrinho</a>
      </p>
    {{ product.description|linebreaks }}
  </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load pagination %}
{% block titulo %}
  Lista de Produtos | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
  <h1>Produtos</h1>
</div>
<div class="row">
  {% for product in product_list  %}
      {% include "catalog/_product.html" %}
  {% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}